site_name: 2020_5BI_Team6

nav:
    - 'Project Charter': 'Project Charter.md'
    - 'Software Requirements Specification': 'software requirements specification.md'
    - 'Software Project Management Plan': 'Software Project_Management_Plan.md'
   
    
theme:
    name: readthedocs

