site_name: 2020 5BI Team2 Software Documentation

nav:
    - 'December':
        - 'Project Charter': 'Project_Charter.md'
        - 'Software Requirements Specification': 'software_requirements_specification.md'
        - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
        - 'Project Model': 'Project_Model.pdf'
        - 'Business Model Canvas': 'business_model_canvas.pdf'
    - 'April':
        - 'Release Plan': 'Release_Plan.md' 
        - 'Iteration Plan': 'Iteration_Plan.md'
        - 'Project Success Criteria': 'Project_Success_Criteria.md'
        - 'Project Closure Report': 'Project_Closure_Report.pdf'
        - 'Status Report': 'Status_Report.pdf' 
        - 'Test Plan': 'Test_Plan.md' 
        - 'Test Case Specification': 'Test_Case_Specification.md'
        - 'User Guide': 'User guide.md'
        - 'System Requirements Documentation': 'documentation_gruia_1.md'
        - 'Data Processing Agreement': 'DPA.md'
    - 'PDF':
        - 'Project Charter': 'Project_Charter.pdf'
        - 'Software Requirements Specification': 'software_requirements_specification.pdf'
        - 'Software Project Management Plan': 'Software_Project_Management_Plan.pdf'
        - 'Project Model': 'Project_Model.pdf'
        - 'Business Model Canvas': 'business_model_canvas.pdf'
        - 'Release Plan': 'Release_Plan.pdf' 
        - 'Iteration Plan': 'Iteration_Plan.pdf'
        - 'Project Success Criteria': 'Project_Success_Criteria.pdf'
        - 'Project Closure Report': 'Project_Closure_Report.pdf'
        - 'Status Report': 'Status_Report.pdf'
        - 'Test Plan': 'Test Plan.pdf'
        - 'Test Case Specification': 'Test_Case_Specification.pdf'
        - 'User Guide': 'User guide.pdf'
        - 'System Requirements Documentation': 'System_Requirements_Documentation.pdf'
        - 'Data Processing Agreement': 'DPA.pdf'
theme:
    name: readthedocs
