site_name: 2020_5BI_Team6

nav:
    - 'Project Charter': 'Project_Charter.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Project Model': 'Project_Model.pdf'
    - 'Test Case Specification': 'Test_Case_Specification.md'
   
    
theme:
    name: readthedocs

